# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Ethnicity',
            field=models.CharField(blank=True, default='Chinese', help_text='Chinese/Malay/Indian/Eurasian/Others', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, default='Male', help_text='Male/Female', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='smoker',
            field=models.CharField(blank=True, default='No', help_text='Yes/No', max_length=3),
        ),
    ]
