# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_auto_20180329_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Ethnicity',
            new_name='ethnicity',
        ),
    ]
