# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
    ]
