# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patients',
            new_name='PatientsInfo',
        ),
    ]
