# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientsinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
