# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20180303_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
