# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20180303_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
