# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientsinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True, validators=[patients.validators.validate_gender]),
        ),
    ]
