# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20180331_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='follow_up_initial_visit',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_admitted_to_edtu',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_at_own_risk_discharges',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_discharged',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='gender',
            field=models.IntegerField(blank=True, default='0', help_text='0=Male, 1=Female', null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_primary_doctor',
            field=models.IntegerField(blank=True, default='1', help_text='1=HO/MO, 2=Locum/GP, 3=Registrar', null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_shift',
            field=models.IntegerField(blank=True, default='1', help_text='1=AM, 2=PM, 3=Night', null=True),
        ),
    ]
