# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20180331_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='activities_of_daily_living',
            field=models.IntegerField(blank=True, default='0', help_text='0=Independent, 1=Assisted, 2=dependent', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='caregiver',
            field=models.IntegerField(blank=True, default='0', help_text='0=Do not have, 1=Have', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='congestive_heart_failure',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='diabetes_mellitus',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='diabetes_mellitus_end_organ_damage',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='mobility',
            field=models.IntegerField(blank=True, default='0', help_text='0=independent, 1=ambulant with assistance, 2=wheelchair, 3=bedbound', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='peripheral_vascular_disease',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
    ]
