# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20180331_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='acute_myocardial_infarction',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='chronic_obstructive_pulmonary_disease',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='metastatic_cancer',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='nonmetastatic_cancer',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='renal_disease',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='transient_ischemic_attack',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
    ]
