# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20180331_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='constipation',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='extend_mc',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_pac',
            field=models.IntegerField(blank=True, default='1', help_text='1=P1, 2=P2, 3=P3', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_pac_vs3',
            field=models.IntegerField(blank=True, default='0', help_text='0=P1&P2, 1=P3', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_pain_score',
            field=models.IntegerField(blank=True, default='0', help_text='0-10', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_vital_signs',
            field=models.IntegerField(blank=True, default='0', help_text='0=Normal, 1=Abnormal', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='musculoskeletal_pain',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='persist_pain',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_pac',
            field=models.IntegerField(blank=True, default='0', help_text='1=P1, 2=P2, 3=P3', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_pac_vs3',
            field=models.IntegerField(blank=True, default='0', help_text='0=P1&P2, 1=P3', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_pain_score',
            field=models.IntegerField(blank=True, default='0', help_text='0-10', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_primary_doctor',
            field=models.IntegerField(blank=True, default='1', help_text='1=HO/MO, 2=Locum/GP, 3=Registrar', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_secondary_doctor',
            field=models.IntegerField(blank=True, default='0', help_text='0=No supervised secondary dcotor, 1=supervised by secondart doctor', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_shift',
            field=models.IntegerField(blank=True, default='1', help_text='1=AM, 2=PM, 3=Night', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='return_vital_signs',
            field=models.IntegerField(blank=True, default='0', help_text='0=Normal, 1=Abnormal', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='sob',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
        migrations.AddField(
            model_name='patientsinfo',
            name='worsen_symptoms_except_pain',
            field=models.IntegerField(blank=True, default='0', help_text='0=No, 1=Yes', null=True),
        ),
    ]
