# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20180331_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsinfo',
            name='category',
        ),
    ]
