# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_patientsinfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
