# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_remove_patientsinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='gender',
            field=models.IntegerField(blank=True, default='0', help_text='0=Male, 1=Female', null=True, validators=[patients.validators.validate_gender]),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_shift',
            field=models.CharField(blank=True, default='AM', help_text='AM/PM/Night', max_length=6, null=True),
        ),
    ]
