# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20180401_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='gender',
            field=models.CharField(blank=True, default='Male', help_text='Male/Female', max_length=6, null=True, validators=[patients.validators.validate_gender]),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_admitted_to_edtu',
            field=models.CharField(blank=True, default='No', help_text='No/Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_primary_doctor',
            field=models.CharField(blank=True, default='HO&MO', help_text='HO&MO / Locum&GP / Registrar', max_length=20, null=True),
        ),
    ]
