# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20180401_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='activities_of_daily_living',
            field=models.CharField(blank=True, default='Independent', help_text='Independent/Assisted/Dependent', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='caregiver',
            field=models.CharField(blank=True, default='Do not have', help_text='Do not have/Have', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='diabetes_mellitus',
            field=models.CharField(blank=True, default='No', help_text='No/Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='diabetes_mellitus_end_organ_damage',
            field=models.CharField(blank=True, default='No', help_text='No/Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='follow_up_initial_visit',
            field=models.CharField(blank=True, default='No', help_text='No/Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_at_own_risk_discharges',
            field=models.CharField(blank=True, default='No', help_text='No/Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_discharged',
            field=models.CharField(blank=True, default='No', help_text='No/Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='mobility',
            field=models.CharField(blank=True, default='Independet', help_text='Independent/Ambulant with Assistance/Wheelchair/Bedbound', max_length=20, null=True),
        ),
    ]
