# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20180401_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='trauma',
            field=models.CharField(blank=True, default='No', help_text='Trauma/No', max_length=30, null=True),
        ),
    ]
