# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20180401_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='chronic_obstructive_pulmonary_disease',
            field=models.CharField(blank=True, default='No', help_text='Chronic Obstructive Pulmonary Disease / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='congestive_heart_failure',
            field=models.CharField(blank=True, default='No', help_text='Congestive Heart Failure', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='diabetes_mellitus',
            field=models.CharField(blank=True, default='No', help_text='Diabetes Mellitus / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='diabetes_mellitus_end_organ_damage',
            field=models.CharField(blank=True, default='No', help_text='Diabetes Mellitus End Organ Damage / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='follow_up_initial_visit',
            field=models.CharField(blank=True, default='No', help_text='Follow up Initial Visit / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='gender',
            field=models.CharField(blank=True, default='Male', help_text='Male / Female', max_length=6, null=True, validators=[patients.validators.validate_gender]),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_admitted_to_edtu',
            field=models.CharField(blank=True, default='No', help_text='Admitted to EDTU / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_at_own_risk_discharges',
            field=models.CharField(blank=True, default='No', help_text='At Own Risk Discharges / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_discharged',
            field=models.CharField(blank=True, default='No', help_text='Discharged / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_shift',
            field=models.CharField(blank=True, default='AM', help_text='AM / PM / Night', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='peripheral_vascular_disease',
            field=models.CharField(blank=True, default='No', help_text='Peripheral Vascular Disease / No', max_length=50, null=True),
        ),
    ]
