# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_auto_20180401_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='abdominal_pain',
            field=models.CharField(blank=True, default='No', help_text='Abdominal Pain / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='activities_of_daily_living',
            field=models.CharField(blank=True, default='Independent', help_text='Independent / Assisted / Dependent', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='acute_myocardial_infarction',
            field=models.CharField(blank=True, default='No', help_text='Acute Myocardial Infarction / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='caregiver',
            field=models.CharField(blank=True, default='Do not have', help_text='Do not have / Have', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='congestive_heart_failure',
            field=models.CharField(blank=True, default='No', help_text='Congestive Heart Failure / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='metastatic_cancer',
            field=models.CharField(blank=True, default='No', help_text='Metastatic Cancer / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='mobility',
            field=models.CharField(blank=True, default='Independet', help_text='Independent/Ambulant with Assistance / Wheelchair / Bedbound', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='nonmetastatic_cancer',
            field=models.CharField(blank=True, default='No', help_text='Nonmetastatic Cancer / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='renal_disease',
            field=models.CharField(blank=True, default='No', help_text='Renal Disease / No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='transient_ischemic_attack',
            field=models.CharField(blank=True, default='No', help_text='Transient Ischemic Attack / No', max_length=50, null=True),
        ),
    ]
