# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20180401_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='asthma',
            field=models.CharField(blank=True, default='No', help_text='Asthma / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='cerebral_palsy',
            field=models.CharField(blank=True, default='No', help_text='Cerebral Palsy / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='constipation',
            field=models.CharField(blank=True, default='No', help_text='Constipation / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='diarrhea',
            field=models.CharField(blank=True, default='No', help_text='Diarrhea / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='fever',
            field=models.CharField(blank=True, default='No', help_text='Fever / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='giddiness',
            field=models.CharField(blank=True, default='No', help_text='Giddiness / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='low_back_pain',
            field=models.CharField(blank=True, default='No', help_text='Low Back Pain / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='musculoskeletal_pain',
            field=models.CharField(blank=True, default='No', help_text='Musculoskeletal Pain / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='nausea_vomiting',
            field=models.CharField(blank=True, default='No', help_text='Nausea Vomiting / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='renal_colic',
            field=models.CharField(blank=True, default='No', help_text='Renal Colic / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='sob',
            field=models.CharField(blank=True, default='No', help_text='Sob / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='upper_respiratory_tract_infections',
            field=models.CharField(blank=True, default='No', help_text='Upper Respiratory Tract Infections / No', max_length=30, null=True),
        ),
    ]
