# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_auto_20180401_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='extend_mc',
            field=models.CharField(blank=True, default='No', help_text='Extend MC / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_pac',
            field=models.CharField(blank=True, default='P1', help_text='P1 / P2 / P3', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='initial_vital_signs',
            field=models.CharField(blank=True, default='Normal', help_text='Normal / Abnormal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='persist_pain',
            field=models.CharField(blank=True, default='No', help_text='Persist Pain / No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='return_pac',
            field=models.CharField(blank=True, default='P1', help_text='P1 / P2 / P3', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='return_primary_doctor',
            field=models.CharField(blank=True, default='HO&MO', help_text='HO&MO / Locum&GP / Registrar', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='return_secondary_doctor',
            field=models.CharField(blank=True, default='No Supervised Secondary Doctor', help_text='No Supervised Secondary Dcotor / Supervised by Secondart Doctor', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='return_shift',
            field=models.CharField(blank=True, default='AM', help_text='AM / PM / Night', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='return_vital_signs',
            field=models.CharField(blank=True, default='Normal', help_text='Normal / Abnormal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsinfo',
            name='worsen_symptoms_except_pain',
            field=models.CharField(blank=True, default='No', help_text='Worsen Symptoms Except Pain / No', max_length=30, null=True),
        ),
    ]
