# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_auto_20180401_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='return_secondary_doctor',
            field=models.CharField(blank=True, default='No Supervised Secondary Doctor', help_text='No Supervised Secondary Dcotor / Supervised by Secondary Doctor', max_length=30, null=True),
        ),
    ]
