# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_auto_20180401_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_secondary_doctor',
            field=models.CharField(blank=True, default='No Supervised Secondary Doctor', help_text='No Supervised Secondary Dcotor / Supervised by Secondary Doctor', max_length=30, null=True),
        ),
    ]
