# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_patientsinfo_initial_secondary_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinfo',
            name='initial_admitted',
            field=models.CharField(blank=True, default='No', help_text='Admitted/ No', max_length=50, null=True),
        ),
    ]
